settings:
  start-y: -64 #岩浆开始上升的坐标
  stop-y: 319 #岩浆最终达到的坐标
  rise-speed: 8 #岩浆多少tick上升一格
  border-start-size: 1000 #边界在开始时的大小
  border-change-size: 50 #边界最终的大小
  border-time: 12000 #边界从开始缩到最终大小的时间，单位：tick
  pvp-start-lava-y: 100 #岩浆上升到多少格开始玩家pvp
